spring:
  application:
    name: qicaiyun
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: none
  devtools:
      restart:
        additional-exclude: resources/**
  thymeleaf:
     cache: false
     prefix: classpath:/webapp/pages/
     suffix: .html
     encoding: UTF-8
#     content-type: text/html
     mode: LEGACYHTML5
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#     mode: HTML5
server:
  port: 9090
  servlet:
    context-path: /qicaiyun
  tomcat:
    uri-encoding: utf-8


#####日志
logging:
  config: classpath:log4j2.xml
  level:
    root: debug
    org:
      springframework:
        web: debug
      hibernate: ERROR
    tk:
      mybatis:
        springboot:
          mapper: trace