spring:
  application:
    name: qicaiyun
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jianshu
    username: root
    password: 1111
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: none

server:
  port: 9090
  context-path: /qicaiyun




#spring.datasource.druid.initial-size=1
#spring.datasource.druid.min-idle=1
#spring.datasource.druid.max-active=20
#spring.datasource.druid.test-on-borrow=true
#spring.datasource.druid.stat-view-servlet.allow=true

#management:
#  security:
#    enabled: false #关掉安全认证
#  context-path: /management #actuator的访问路径　
#
#
#druid:
#  pool:
#    initialSize: 10
#    maxActive: 100
#    minIdle: 10
#
#

#mybatis-plus
##NOTE:configLocation与configuration不可以同时设定
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.cqs.qicaiyun.modules.entity
  configLocation: classpath:mybatis-config.xml
  global-config:
    id-type: 3
    field-strategy: 2
    auto-set-db-type: true
    db-column-underline: true
    refresh-mapper: true
  check-config-location: true
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false



#####日志
logging:
  config: classpath:log4j2.xml
  level:
    root: WARN
    org:
      springframework:
        web: WARE
      hibernate: ERROR
    tk:
      mybatis:
        springboot:
          mapper: trace