spring:

  redis:
     database: 0
     host: qcy.redis.com
     port: 6379
     password:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://qcy.mysql.com:3306/qicaiyun
    username: root
    password: 1111
    druid:
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat, wall, slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  data:
    mongodb:
      host: qcy.mongo.com
      port: 27017
      authentication-database: admin
      ## 高版本的mongo需要用uri的方式连接
      uri: mongodb://dev:1111@qcy.mongo.com:27017/qicaiyun
#    initialSize: 5

#####日志
logging:
  config: classpath:log4j2.xml
  level:
    root: WARN
    org:
      springframework:
        web: WARN
      hibernate: ERROR
    tk:
      mybatis:
        springboot:
          mapper: trace