spring:
  application:
    name: qicaiyun
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qicaiyun
    username: root
    password: 1111
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  session:
    store-type: none
  mvc:
      view:
        prefix: /WEB-INF/view/
        suffix: .jsp
  devtools:
      restart:
        additional-exclude: scripts/**,template/**,resources/**,WEB-INF/**


server:
  port: 9090
  context-path: /qicaiyun








#spring.datasource.druid.initial-size=1
#spring.datasource.druid.min-idle=1
#spring.datasource.druid.max-active=20
#spring.datasource.druid.test-on-borrow=true
#spring.datasource.druid.stat-view-servlet.allow=true

#management:
#  security:
#    enabled: false #关掉安全认证
#  context-path: /management #actuator的访问路径　
#
#
#druid:
#  pool:
#    initialSize: 10
#    maxActive: 100
#    minIdle: 10
#
#

#mybatis-plus
##NOTE:configLocation与configuration不可以同时设定
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.cqs.qicaiyun.modules.entity
  ###没起作用
  configLocation: classpath:/mybatis-config.xml
#
#  global-config:
##    值	描述
##    IdType.AUTO	数据库ID自增
##    IdType.INPUT	用户输入ID
##    IdType.ID_WORKER	全局唯一ID，内容为空自动填充（默认配置）
##    IdType.UUID	全局唯一ID，内容为空自动填充
#    id-type: 0
#    field-strategy: 2
#    db-column-underline: true
#    refresh-mapper: true
#  check-config-location: true
##  configuration:
##    cache-enabled: false
##    map-underscore-to-camel-case: true
#


#####日志
logging:
  config: classpath:log4j2.xml
  level:
    root: WARN
    org:
      springframework:
        web: WARN
      hibernate: ERROR
    tk:
      mybatis:
        springboot:
          mapper: trace